interface Chatroom {
  userIdx?: number,
  creator?: string,
  sessionId?: string,
  roomName?: string,
  pwd?: string,
  usePwd?: boolean,
  usePrivate?: boolean,
  useRtc?: boolean,
  currentUserCount?: number,
  maxUserCount?: number,
  createDate?: string,
  updateDate?: string,
  createDatetime?: string,
}