name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set environment variables
      run: |
        echo "API_DOMAIN=$API_DOMAIN" >> .env
        echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
        echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
        echo "KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID" >> .env
        echo "KAKAO_CLIENT_SECRET=$KAKAO_CLIENT_SECRET" >> .env
        echo "NAVER_CLIENT_ID=$NAVER_CLIENT_ID" >> .env
        echo "NAVER_CLIENT_SECRET=$NAVER_CLIENT_SECRET" >> .env
        echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env
        echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env
        echo "NEXT_PUBLIC_BASE_PATH=$NEXT_PUBLIC_BASE_PATH" >> .env
      env:
        API_DOMAIN: ${{ secrets.API_DOMAIN }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
        KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
        NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
        NAVER_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_BASE_PATH }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
        NEXT_PUBLIC_BASE_PATH: ${{ secrets.NEXT_PUBLIC_BASE_PATH }}

    - name: Build the Docker image
      run: |
        TIMESTAMP=$(date -d "${{ github.event.head_commit.timestamp }}" '+%Y%m%d%H%M%S')
        docker buildx build --platform linux/amd64 -t hjproject.kro.kr/chatforyou/nextjs-app:$TIMESTAMP --push .
